name: Build Mac Intel DMG

on:
  workflow_dispatch: # Allows you to trigger the build manually from GitHub

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Mac x64 DMG
        run: npx electron-builder --mac --x64 --publish never

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Palimpsest-Mac-Intel-DMG
          path: release/*.dmg